# Generated by Django 6.0.6 on 2026-06-20 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Direct image URL for the company logo'),
        ),
        migrations.AddField(
            model_name='job',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_criteria',
            field=models.CharField(blank=True, help_text="e.g. 'B.Tech/B.E, CGPA >= 7.0'", max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, default='Fresher', max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('resume_shortlisted', 'Resume Shortlisted'), ('aptitude_test', 'Aptitude Test'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=24),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='Full-time', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('resume_shortlisted', 'Resume Shortlisted'), ('aptitude_test', 'Aptitude Test'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
