# Generated by Django 6.0.6 on 2026-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_description_company_hq_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eligible_branches',
            field=models.CharField(blank=True, help_text="Comma-separated branch codes (e.g. 'CSE,IT'). Blank = open to all branches.", max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='min_cgpa',
            field=models.FloatField(default=0, help_text='Minimum CGPA required to apply. 0 = no minimum.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='eligibility_criteria',
            field=models.CharField(blank=True, help_text="e.g. 'B.Tech/B.E, CGPA >= 7.0' (descriptive text shown to students)", max_length=255),
        ),
    ]
