# Curated question bank for the AI Mock Interview module.
# Each entry: role, interview_type, difficulty, question_format, question_text,
# expected_keywords (comma-separated concepts used for rule-based scoring),
# sample_answer (shown to the student as a model answer after they respond).

APTITUDE = [
    dict(role="Any", interview_type="aptitude", difficulty="easy", question_format="concept",
         question_text="A train travels 60 km in 1.5 hours. What is its speed in km/h?",
         expected_keywords="40, speed, distance, time, divide",
         sample_answer="Speed = Distance / Time = 60 / 1.5 = 40 km/h."),
    dict(role="Any", interview_type="aptitude", difficulty="easy", question_format="concept",
         question_text="If a shirt costs ₹800 after a 20% discount, what was its original price?",
         expected_keywords="1000, discount, percentage, original price",
         sample_answer="800 is 80% of the original price, so original = 800 / 0.8 = ₹1000."),
    dict(role="Any", interview_type="aptitude", difficulty="easy", question_format="concept",
         question_text="What is the next number in the series: 2, 4, 8, 16, ?",
         expected_keywords="32, double, pattern, multiply by 2",
         sample_answer="Each term doubles the previous one, so the next number is 32."),
    dict(role="Any", interview_type="aptitude", difficulty="medium", question_format="concept",
         question_text="Two pipes can fill a tank in 6 hours and 8 hours respectively. How long will it take if both are opened together?",
         expected_keywords="rate, LCM, 24/7, work, combined rate",
         sample_answer="Combined rate = 1/6 + 1/8 = 7/24 per hour, so time = 24/7 ≈ 3.43 hours."),
    dict(role="Any", interview_type="aptitude", difficulty="medium", question_format="concept",
         question_text="A is twice as old as B. Five years ago, A was three times as old as B. Find their current ages.",
         expected_keywords="equation, age, twice, linear equation, 20, 10",
         sample_answer="Let B = x, A = 2x. (2x-5) = 3(x-5) => 2x-5=3x-15 => x=10, so B=10, A=20."),
    dict(role="Any", interview_type="aptitude", difficulty="medium", question_format="concept",
         question_text="In how many ways can the letters of the word 'TABLE' be arranged?",
         expected_keywords="permutation, factorial, 120, 5!",
         sample_answer="All 5 letters are distinct, so arrangements = 5! = 120."),
    dict(role="Any", interview_type="aptitude", difficulty="hard", question_format="concept",
         question_text="A boat travels 30 km upstream in 6 hours and the same distance downstream in 3 hours. Find the speed of the boat and the current.",
         expected_keywords="upstream, downstream, relative speed, 7.5, 2.5",
         sample_answer="Upstream speed = 5 km/h, downstream = 10 km/h. Boat speed = (10+5)/2 = 7.5 km/h, current = (10-5)/2 = 2.5 km/h."),
    dict(role="Any", interview_type="aptitude", difficulty="hard", question_format="concept",
         question_text="If the probability of an event is 0.3, what is the probability that it does NOT occur in 2 independent trials?",
         expected_keywords="0.49, independent, complement, 0.7, probability",
         sample_answer="P(not occur once) = 0.7. For 2 independent trials, P(never occurs) = 0.7 × 0.7 = 0.49."),
    dict(role="Any", interview_type="aptitude", difficulty="hard", question_format="concept",
         question_text="A sum of money doubles itself in 8 years at simple interest. In how many years will it triple?",
         expected_keywords="simple interest, rate, 16, double, triple",
         sample_answer="Doubling in 8 years means rate = 12.5%/year. To triple (gain = 2x principal) takes 2/0.125 = 16 years."),
    dict(role="Any", interview_type="aptitude", difficulty="medium", question_format="concept",
         question_text="What is the time complexity of binary search, and why?",
         expected_keywords="O(log n), divide, sorted array, halves",
         sample_answer="O(log n) - each comparison halves the search space, so it takes log base 2 of n steps."),
]

HR = [
    dict(role="Any", interview_type="hr", difficulty="easy", question_format="concept",
         question_text="Tell me about yourself.",
         expected_keywords="background, education, skills, projects, goals",
         sample_answer="A strong answer briefly covers your education, key skills, 1-2 standout projects/experiences, and what you're looking for next - in under a minute."),
    dict(role="Any", interview_type="hr", difficulty="easy", question_format="concept",
         question_text="Why do you want to work for our company?",
         expected_keywords="research, mission, values, growth, role fit",
         sample_answer="Mention something specific about the company's mission/products you researched, and connect it to your own skills and career goals."),
    dict(role="Any", interview_type="hr", difficulty="easy", question_format="concept",
         question_text="What are your greatest strengths?",
         expected_keywords="specific strength, example, impact, relevant to role",
         sample_answer="Name 1-2 genuine strengths relevant to the role and back each with a brief concrete example of when you used it."),
    dict(role="Any", interview_type="hr", difficulty="medium", question_format="concept",
         question_text="What is your biggest weakness, and how are you working on it?",
         expected_keywords="self-awareness, honest, improvement plan, example",
         sample_answer="Pick a real, minor weakness, show self-awareness, and describe a concrete step you're taking to improve - avoid clichés like 'I'm a perfectionist'."),
    dict(role="Any", interview_type="hr", difficulty="medium", question_format="concept",
         question_text="Where do you see yourself in 5 years?",
         expected_keywords="growth, skills, leadership, realistic, role-related",
         sample_answer="Describe realistic growth (e.g. deeper technical expertise or growing into a senior/lead role) tied to the company's career path, not an unrelated dream job."),
    dict(role="Any", interview_type="hr", difficulty="medium", question_format="concept",
         question_text="Why should we hire you over other candidates?",
         expected_keywords="unique value, skills, evidence, fit",
         sample_answer="Summarize 2-3 concrete things that differentiate you (skills, projects, attitude) and tie them directly to what the role needs."),
    dict(role="Any", interview_type="hr", difficulty="hard", question_format="concept",
         question_text="Tell me about a time you disagreed with your manager or team lead. How did you handle it?",
         expected_keywords="situation, respectful, communication, outcome, compromise",
         sample_answer="Use the STAR method: describe the situation, how you raised your concern respectfully with reasoning, and the outcome/what you learned."),
    dict(role="Any", interview_type="hr", difficulty="hard", question_format="concept",
         question_text="Describe a situation where you failed. What did you learn from it?",
         expected_keywords="honest, ownership, lesson learned, changed behavior",
         sample_answer="Pick a real failure, take ownership without over-blaming yourself or others, and clearly state the lesson and how it changed your approach since."),
]

BEHAVIORAL = [
    dict(role="Any", interview_type="behavioral", difficulty="easy", question_format="concept",
         question_text="Describe a project you're proud of and your specific role in it.",
         expected_keywords="situation, task, action, result, your role",
         sample_answer="Use STAR: briefly set the context, explain what YOU specifically did (not just the team), and quantify the result if possible."),
    dict(role="Any", interview_type="behavioral", difficulty="easy", question_format="concept",
         question_text="Tell me about a time you worked in a team to solve a difficult problem.",
         expected_keywords="teamwork, collaboration, problem, outcome, communication",
         sample_answer="Describe the problem, how the team divided work and communicated, your specific contribution, and the result."),
    dict(role="Any", interview_type="behavioral", difficulty="medium", question_format="concept",
         question_text="Describe a time you had to learn a new technology quickly under a deadline.",
         expected_keywords="learning, deadline, resourcefulness, outcome, time management",
         sample_answer="Explain the pressure/deadline, how you prioritized learning (docs, tutorials, asking for help), and the result you delivered."),
    dict(role="Any", interview_type="behavioral", difficulty="medium", question_format="concept",
         question_text="Tell me about a time you had to manage multiple priorities at once.",
         expected_keywords="prioritization, time management, organization, outcome",
         sample_answer="Describe how you assessed urgency/impact of each task, the system you used to organize them, and the outcome."),
    dict(role="Any", interview_type="behavioral", difficulty="medium", question_format="concept",
         question_text="Describe a time you received critical feedback. How did you respond?",
         expected_keywords="openness, growth mindset, action taken, improvement",
         sample_answer="Show you listened without defensiveness, took specific action based on the feedback, and improved as a result."),
    dict(role="Any", interview_type="behavioral", difficulty="hard", question_format="concept",
         question_text="Tell me about a time you took initiative on something outside your defined responsibilities.",
         expected_keywords="initiative, ownership, impact, proactive",
         sample_answer="Describe the gap you noticed, why you decided to act despite it not being 'your job', and the positive impact it had."),
    dict(role="Any", interview_type="behavioral", difficulty="hard", question_format="concept",
         question_text="Describe a time a project you worked on did not go as planned. What did you do?",
         expected_keywords="setback, adaptability, problem solving, communication, recovery",
         sample_answer="Explain what went wrong, how you adapted the plan or communicated the risk early, and how the situation was ultimately resolved."),
    dict(role="Any", interview_type="behavioral", difficulty="hard", question_format="concept",
         question_text="Tell me about a time you had to convince others to adopt your idea or approach.",
         expected_keywords="persuasion, data, communication, stakeholders, outcome",
         sample_answer="Describe how you backed your idea with evidence/data, addressed others' concerns, and the eventual outcome."),
]

GENERIC_TECHNICAL = [
    dict(role="Any", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between a stack and a queue?",
         expected_keywords="LIFO, FIFO, push, pop, enqueue, dequeue",
         sample_answer="A stack is LIFO (Last In First Out) using push/pop; a queue is FIFO (First In First Out) using enqueue/dequeue."),
    dict(role="Any", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between a process and a thread?",
         expected_keywords="memory space, lightweight, shared memory, independent execution",
         sample_answer="A process has its own memory space and is independent; threads run within a process and share its memory, making them lighter-weight."),
    dict(role="Any", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain the difference between SQL and NoSQL databases, with an example use case for each.",
         expected_keywords="schema, relational, scalability, flexibility, structured, unstructured",
         sample_answer="SQL databases are relational with a fixed schema (e.g. banking systems needing strong consistency); NoSQL databases are schema-flexible and scale horizontally (e.g. storing varied user activity logs)."),
    dict(role="Any", interview_type="technical", difficulty="medium", question_format="coding",
         question_text="Explain your approach to writing a function that reverses a string in-place. What's the time/space complexity?",
         expected_keywords="two pointers, swap, O(n), O(1), in-place",
         sample_answer="Use two pointers from both ends, swapping characters and moving inward until they meet - O(n) time and O(1) extra space."),
    dict(role="Any", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you find the second largest number in an unsorted array without sorting it? Explain your approach and complexity.",
         expected_keywords="single pass, O(n), track two variables, edge cases",
         sample_answer="Track the largest and second-largest while scanning once: update both as you go, handling duplicates/edge cases - O(n) time, O(1) space."),
    dict(role="Any", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="What is the CAP theorem and why does it matter for distributed systems?",
         expected_keywords="consistency, availability, partition tolerance, tradeoff, distributed",
         sample_answer="CAP theorem says a distributed system can only fully guarantee 2 of 3: Consistency, Availability, Partition tolerance - real systems pick tradeoffs based on their needs."),
]

JAVA_DEVELOPER = [
    dict(role="Java Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between JDK, JRE, and JVM?",
         expected_keywords="development kit, runtime environment, virtual machine, compile, execute",
         sample_answer="JDK is the full development kit (includes compiler); JRE is what's needed to run Java apps; JVM is the engine that actually executes bytecode."),
    dict(role="Java Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between '==' and '.equals()' in Java?",
         expected_keywords="reference comparison, value comparison, object, memory address",
         sample_answer="'==' compares object references (memory addresses) for objects, while '.equals()' compares actual content/value, assuming it's overridden properly."),
    dict(role="Java Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain the difference between an abstract class and an interface in Java.",
         expected_keywords="multiple inheritance, default methods, state, abstract methods",
         sample_answer="An abstract class can hold state and some implemented methods but supports only single inheritance; an interface defines a contract (with default methods allowed) and supports multiple inheritance."),
    dict(role="Java Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the purpose of the 'static' keyword in Java?",
         expected_keywords="class level, shared, memory, no instance needed",
         sample_answer="'static' members belong to the class itself rather than any instance, so they're shared across all objects and can be accessed without creating an instance."),
    dict(role="Java Developer", interview_type="technical", difficulty="medium", question_format="coding",
         question_text="How would you detect and avoid a ConcurrentModificationException when removing items from a List while iterating?",
         expected_keywords="iterator.remove, CopyOnWriteArrayList, removeIf, concurrent modification",
         sample_answer="Use Iterator.remove(), Collection.removeIf(), or a CopyOnWriteArrayList instead of modifying a list directly inside a for-each loop."),
    dict(role="Java Developer", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="Explain how Java's Garbage Collector decides when to reclaim memory, and name one GC algorithm.",
         expected_keywords="heap, reachability, generational, G1, mark and sweep",
         sample_answer="The GC reclaims objects no longer reachable from GC roots, often using generational collection (young/old gen); G1 and CMS are common collector algorithms."),
    dict(role="Java Developer", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you design a thread-safe Singleton class in Java? Walk through your approach.",
         expected_keywords="double-checked locking, volatile, synchronized, enum singleton",
         sample_answer="Use double-checked locking with a volatile instance variable, or simply declare the singleton as an enum, which is inherently thread-safe."),
    dict(role="Java Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What are Java Streams and how do they differ from traditional loops?",
         expected_keywords="functional, lazy evaluation, pipeline, map, filter, declarative",
         sample_answer="Streams provide a declarative, functional way to process collections (map/filter/reduce) with lazy evaluation, often more concise than imperative loops."),
]

PYTHON_DEVELOPER = [
    dict(role="Python Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between a list and a tuple in Python?",
         expected_keywords="mutable, immutable, performance, syntax",
         sample_answer="Lists are mutable (can be changed after creation) using [], tuples are immutable using (), and tuples are slightly faster/more memory-efficient."),
    dict(role="Python Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the Global Interpreter Lock (GIL) in Python?",
         expected_keywords="single thread, bytecode, CPython, concurrency limitation",
         sample_answer="The GIL is a mutex in CPython that allows only one thread to execute Python bytecode at a time, limiting true multi-threaded CPU-bound parallelism."),
    dict(role="Python Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain list comprehensions and give an example of when you'd use one.",
         expected_keywords="concise, readable, for loop, filter, map equivalent",
         sample_answer="List comprehensions provide a concise, readable way to build lists, e.g. [x*x for x in range(10) if x % 2 == 0] replaces a multi-line loop."),
    dict(role="Python Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What are Python decorators and how do they work?",
         expected_keywords="function wrapping, @ syntax, higher-order function, closures",
         sample_answer="Decorators wrap a function to extend its behavior without modifying it directly, implemented as higher-order functions using the @decorator syntax."),
    dict(role="Python Developer", interview_type="technical", difficulty="medium", question_format="coding",
         question_text="How would you remove duplicates from a list while preserving order? Explain your approach.",
         expected_keywords="dict.fromkeys, set, order preserving, O(n)",
         sample_answer="Use dict.fromkeys(list) which preserves insertion order since Python 3.7, or iterate while tracking seen items in a set - both O(n)."),
    dict(role="Python Developer", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="Explain the difference between multiprocessing and multithreading in Python, and when you'd use each.",
         expected_keywords="GIL, CPU-bound, I/O-bound, separate processes, shared memory",
         sample_answer="Multithreading is good for I/O-bound tasks (limited by GIL for CPU work); multiprocessing spawns separate processes with their own memory, bypassing the GIL for true CPU-bound parallelism."),
    dict(role="Python Developer", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you implement a simple LRU cache in Python? Describe the data structures you'd use.",
         expected_keywords="OrderedDict, hashmap, doubly linked list, O(1)",
         sample_answer="Use an OrderedDict (or a hashmap + doubly linked list) to get O(1) get/put while evicting the least-recently-used item when capacity is exceeded."),
    dict(role="Python Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between '*args' and '**kwargs' in Python function definitions?",
         expected_keywords="positional arguments, keyword arguments, variable length, tuple, dict",
         sample_answer="*args collects extra positional arguments into a tuple; **kwargs collects extra keyword arguments into a dict."),
]

FULL_STACK_DEVELOPER = [
    dict(role="Full Stack Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between frontend and backend development?",
         expected_keywords="client-side, server-side, UI, database, API",
         sample_answer="Frontend handles what users see/interact with (UI, client-side logic); backend handles servers, databases, and business logic, usually exposed via APIs."),
    dict(role="Full Stack Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is a RESTful API?",
         expected_keywords="stateless, HTTP methods, resources, JSON, endpoints",
         sample_answer="A REST API exposes resources via URLs and standard HTTP methods (GET/POST/PUT/DELETE), is stateless, and typically exchanges data as JSON."),
    dict(role="Full Stack Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain how JWT authentication works end to end.",
         expected_keywords="token, sign in, header, payload, signature, stateless",
         sample_answer="On login the server issues a signed JWT (header+payload+signature); the client sends it in the Authorization header on future requests, and the server verifies the signature without needing server-side session storage."),
    dict(role="Full Stack Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between SQL JOINs - INNER, LEFT, and RIGHT?",
         expected_keywords="matching rows, all left rows, all right rows, NULL",
         sample_answer="INNER JOIN returns only matching rows in both tables; LEFT JOIN returns all left rows plus matches (NULL if none); RIGHT JOIN is the mirror, keeping all right rows."),
    dict(role="Full Stack Developer", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="How would you design the architecture for a scalable e-commerce checkout system?",
         expected_keywords="load balancing, caching, database, microservices, queue, idempotency",
         sample_answer="Discuss a load-balanced API layer, caching for product data, a message queue for order processing, idempotent payment handling, and a database designed to avoid double-charging under high concurrency."),
    dict(role="Full Stack Developer", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you design a rate limiter for an API? Describe at least one algorithm.",
         expected_keywords="token bucket, sliding window, fixed window, Redis",
         sample_answer="A common approach is the token bucket or sliding window algorithm, often implemented with Redis to track request counts per user/IP within a time window."),
    dict(role="Full Stack Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is CORS and why does it matter when building full-stack apps?",
         expected_keywords="cross-origin, browser security, headers, same-origin policy",
         sample_answer="CORS is a browser security mechanism that restricts cross-origin requests unless the server explicitly allows them via response headers - critical when frontend and backend run on different ports/domains."),
]

FRONTEND_DEVELOPER = [
    dict(role="Frontend Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the virtual DOM in React, and why is it used?",
         expected_keywords="diffing, performance, re-render, real DOM, reconciliation",
         sample_answer="The virtual DOM is an in-memory representation of the UI; React diffs it against the previous version and only updates the real DOM where needed, improving performance."),
    dict(role="Frontend Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between 'let', 'const', and 'var' in JavaScript?",
         expected_keywords="block scope, function scope, reassignment, hoisting",
         sample_answer="'var' is function-scoped and hoisted; 'let' and 'const' are block-scoped, with 'const' disallowing reassignment after declaration."),
    dict(role="Frontend Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain the difference between useState and useEffect in React.",
         expected_keywords="state management, side effects, re-render, dependency array",
         sample_answer="useState manages local component state and triggers a re-render on change; useEffect runs side effects (data fetching, subscriptions) after render, controlled by its dependency array."),
    dict(role="Frontend Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is CSS specificity and how is it calculated?",
         expected_keywords="inline styles, IDs, classes, elements, cascade",
         sample_answer="Specificity determines which CSS rule wins, ranked roughly: inline styles > IDs > classes/attributes > element selectors, with ties broken by source order."),
    dict(role="Frontend Developer", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="How would you optimize the performance of a React app rendering a very large list?",
         expected_keywords="virtualization, memoization, key prop, windowing, React.memo",
         sample_answer="Use list virtualization/windowing (render only visible rows), memoize components with React.memo/useMemo, and ensure stable, unique keys to avoid unnecessary re-renders."),
    dict(role="Frontend Developer", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you implement debounced search input in React? Walk through your approach.",
         expected_keywords="setTimeout, useEffect, cleanup, debounce, delay",
         sample_answer="Use useEffect with a setTimeout that fires the search after a delay, clearing the previous timeout on every keystroke (cleanup function) to avoid firing on every render."),
    dict(role="Frontend Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between server-side rendering (SSR) and client-side rendering (CSR)?",
         expected_keywords="initial load, SEO, hydration, time to interactive",
         sample_answer="SSR renders HTML on the server for faster initial load and better SEO, then 'hydrates' on the client; CSR ships a near-empty HTML shell and renders everything via JS in the browser."),
]

BACKEND_DEVELOPER = [
    dict(role="Backend Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between authentication and authorization?",
         expected_keywords="identity verification, permissions, who you are, what you can do",
         sample_answer="Authentication verifies who you are (login); authorization determines what you're allowed to do once authenticated (permissions/roles)."),
    dict(role="Backend Developer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is database indexing and why does it speed up queries?",
         expected_keywords="lookup speed, B-tree, trade-off write speed, search",
         sample_answer="An index is a separate data structure (often a B-tree) that lets the database find rows without scanning the whole table, at the cost of slightly slower writes."),
    dict(role="Backend Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain database normalization and why it matters.",
         expected_keywords="redundancy, data integrity, normal forms, relationships",
         sample_answer="Normalization organizes tables to reduce data redundancy and improve integrity by splitting data into related tables following normal forms (1NF, 2NF, 3NF)."),
    dict(role="Backend Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between horizontal and vertical scaling?",
         expected_keywords="add servers, bigger server, distributed, single machine",
         sample_answer="Vertical scaling adds more resources (CPU/RAM) to a single server; horizontal scaling adds more servers/instances and distributes load across them."),
    dict(role="Backend Developer", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="How would you design a system to handle 1 million concurrent users on an API?",
         expected_keywords="load balancer, caching, horizontal scaling, database replication, queue",
         sample_answer="Discuss load balancers distributing traffic across many stateless app servers, caching (Redis) for hot data, read replicas for the database, and async queues for heavy background work."),
    dict(role="Backend Developer", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you prevent race conditions when two requests try to decrement the same inventory count simultaneously?",
         expected_keywords="database transaction, locking, atomic operation, optimistic locking",
         sample_answer="Use database-level atomic operations or transactions with row-level locking (or optimistic locking with a version column) so concurrent decrements don't both succeed past zero."),
    dict(role="Backend Developer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between synchronous and asynchronous processing, with an example?",
         expected_keywords="blocking, non-blocking, queue, background job, response time",
         sample_answer="Synchronous processing blocks until the task finishes (e.g. waiting for a DB query); asynchronous processing (e.g. sending emails via a background queue) lets the request return immediately while work continues separately."),
]

DATA_ANALYST = [
    dict(role="Data Analyst", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between mean, median, and mode?",
         expected_keywords="average, middle value, most frequent, central tendency",
         sample_answer="Mean is the average, median is the middle value when sorted, and mode is the most frequently occurring value - all measures of central tendency."),
    dict(role="Data Analyst", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is the difference between INNER JOIN and LEFT JOIN in SQL?",
         expected_keywords="matching rows only, all left rows, NULL values",
         sample_answer="INNER JOIN returns only rows with matches in both tables; LEFT JOIN returns all rows from the left table, filling in NULLs where there's no match on the right."),
    dict(role="Data Analyst", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="How would you detect and handle outliers in a dataset?",
         expected_keywords="IQR, z-score, boxplot, domain knowledge, capping",
         sample_answer="Use statistical methods like IQR or z-score thresholds, visualize with boxplots, and decide whether to cap, remove, or investigate outliers based on domain context."),
    dict(role="Data Analyst", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between correlation and causation?",
         expected_keywords="relationship, confounding variable, experiment, not imply",
         sample_answer="Correlation means two variables move together; causation means one directly causes the other. Correlation does not imply causation - confounding variables or experiments are needed to establish causality."),
    dict(role="Data Analyst", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="How would you measure whether a new feature actually improved user engagement?",
         expected_keywords="A/B test, control group, statistical significance, metric definition",
         sample_answer="Run an A/B test with a control group, define a clear engagement metric upfront, and check for statistical significance before attributing any change to the feature."),
    dict(role="Data Analyst", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you write a SQL query to find the second-highest salary in an Employees table?",
         expected_keywords="subquery, LIMIT OFFSET, DENSE_RANK, MAX excluding",
         sample_answer="One approach: SELECT MAX(salary) FROM Employees WHERE salary < (SELECT MAX(salary) FROM Employees); or use DENSE_RANK() and filter rank = 2."),
    dict(role="Data Analyst", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between a dashboard and a report?",
         expected_keywords="real-time, interactive, static, summary, periodic",
         sample_answer="A dashboard is typically interactive and near real-time, giving an at-a-glance view of key metrics; a report is usually a more detailed, static summary produced periodically."),
]

SOFTWARE_ENGINEER = [
    dict(role="Software Engineer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is Object-Oriented Programming, and what are its 4 main pillars?",
         expected_keywords="encapsulation, inheritance, polymorphism, abstraction",
         sample_answer="OOP organizes code around objects. Its 4 pillars are encapsulation (bundling data+behavior), inheritance (reuse via hierarchy), polymorphism (one interface, many forms), and abstraction (hiding complexity)."),
    dict(role="Software Engineer", interview_type="technical", difficulty="easy", question_format="concept",
         question_text="What is Big-O notation and why does it matter?",
         expected_keywords="time complexity, growth rate, worst case, scalability",
         sample_answer="Big-O describes how an algorithm's runtime/space grows with input size in the worst case, helping compare algorithms' scalability independent of hardware."),
    dict(role="Software Engineer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="Explain the difference between unit testing, integration testing, and end-to-end testing.",
         expected_keywords="isolated component, multiple components, full system, test pyramid",
         sample_answer="Unit tests check isolated functions/components; integration tests check how multiple components work together; end-to-end tests validate the full system flow like a real user would."),
    dict(role="Software Engineer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the SOLID principle of 'Single Responsibility', and why is it useful?",
         expected_keywords="one reason to change, maintainability, separation of concerns",
         sample_answer="A class/module should have only one reason to change - one responsibility - which makes code easier to maintain, test, and reason about."),
    dict(role="Software Engineer", interview_type="technical", difficulty="hard", question_format="concept",
         question_text="How would you design a URL shortener service like bit.ly?",
         expected_keywords="hashing, base62, database, collision, caching, redirect",
         sample_answer="Generate a short unique key (e.g. base62 encoding of an auto-increment ID or hash with collision handling), store the mapping in a database with caching for hot URLs, and redirect with a 301/302 on lookup."),
    dict(role="Software Engineer", interview_type="technical", difficulty="hard", question_format="coding",
         question_text="How would you detect a cycle in a linked list? Explain your approach and complexity.",
         expected_keywords="Floyd's algorithm, two pointers, slow fast, O(n), O(1)",
         sample_answer="Use Floyd's cycle detection (two pointers, slow and fast) - if they ever meet, there's a cycle. O(n) time, O(1) space."),
    dict(role="Software Engineer", interview_type="technical", difficulty="medium", question_format="concept",
         question_text="What is the difference between version control merge and rebase in Git?",
         expected_keywords="commit history, linear history, merge commit, rewriting commits",
         sample_answer="Merge combines branches with a new merge commit, preserving full history; rebase replays your commits on top of another branch, producing a cleaner, linear history but rewriting commit hashes."),
]

QUESTION_BANK = (
    APTITUDE + HR + BEHAVIORAL + GENERIC_TECHNICAL
    + JAVA_DEVELOPER + PYTHON_DEVELOPER + FULL_STACK_DEVELOPER
    + FRONTEND_DEVELOPER + BACKEND_DEVELOPER + DATA_ANALYST + SOFTWARE_ENGINEER
)

ROLES = [
    "Java Developer", "Python Developer", "Full Stack Developer", "Frontend Developer",
    "Backend Developer", "Data Analyst", "Software Engineer",
]
