# Generated by Django 6.0.6 on 2026-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Original uploaded resume file', null=True, upload_to='resumes/'),
        ),
    ]
