# Generated by Django 6.0.6 on 2026-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledinterview',
            name='student_message',
            field=models.CharField(blank=True, help_text="Student's note, e.g. reason for reschedule request", max_length=255),
        ),
        migrations.AddField(
            model_name='scheduledinterview',
            name='student_response',
            field=models.CharField(choices=[('pending', 'Awaiting response'), ('confirmed', 'Confirmed'), ('decline_requested', 'Reschedule requested')], default='pending', max_length=20),
        ),
    ]
